<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG9Ee6y1\App_Kernel1DebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG9Ee6y1/App_Kernel1DebugContainer.php') {
    touch(__DIR__.'/ContainerG9Ee6y1.legacy');

    return;
}

if (!\class_exists(App_Kernel1DebugContainer::class, false)) {
    \class_alias(\ContainerG9Ee6y1\App_Kernel1DebugContainer::class, App_Kernel1DebugContainer::class, false);
}

return new \ContainerG9Ee6y1\App_Kernel1DebugContainer([
    'container.build_hash' => 'G9Ee6y1',
    'container.build_id' => 'd910036d',
    'container.build_time' => 1677597992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG9Ee6y1');
