controllers:
  resource:
    path: ../src/Controller
    namespace: App\Controller
  type: attribute

my_update_boolean:
  path: /my/update-boolean
  controller: App\Controller\ReactionController::updateBoolean
