<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3VFCSIf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3VFCSIf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3VFCSIf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3VFCSIf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3VFCSIf\App_KernelDevDebugContainer([
    'container.build_hash' => '3VFCSIf',
    'container.build_id' => '7e7d1671',
    'container.build_time' => 1678806885,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3VFCSIf');
